### PR TITLE
System.Drawing.Common not working on linux, change it to SixLabors.ImageSharp

### PR DESCRIPTION
**Pull request by arashkey**
System.Drawing.Common not working on linux, change it to SixLabors.ImageSharp

### CODE REVIEW

**Comment by qiuhaotc** [comment]
System.Drawing.Common can be working on Linux, you need to run command ```apt-get update && apt-get install -y libgdiplus``` to install ```libgdiplus```

**Comment by arashkey** [comment]
This is correct, but what about docker? I think it's easier to change the package for running program everywhere with every config.
And also get the latest font name from the system and this solution works on Linux and Windows.

**Comment by qiuhaotc** [comment]
Totally agree, I am also trying to get rid of System.Drawing.Common, if you check this file, I have put the install command at the top https://github.com/qiuhaotc/WebSSH/blob/ff9aeeafafaf9e09b976754f9e97286486ad868a/src/WebSSH/Server/Dockerfile#L4

**Comment by qiuhaotc** [comment]
I will check the PR recently, some parts I might format or delete later, thanks anyway.

**Comment by qiuhaotc** [comment]
ok

**Comment by arashkey** [comment]
Tanks a lot 🤝 
Can you update docker file please ? ☺️

**Comment by qiuhaotc** [comment]
> Tanks a lot 🤝 Can you update docker file please ? ☺️

Already done👍

**Pull request merged**
